/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlansIndexImport } from './routes/plans/index'
import { Route as PlansNewImport } from './routes/plans/new'
import { Route as PlansPlanIdImport } from './routes/plans/$planId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlansIndexRoute = PlansIndexImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRoute,
} as any)

const PlansNewRoute = PlansNewImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => rootRoute,
} as any)

const PlansPlanIdRoute = PlansPlanIdImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdImport
      parentRoute: typeof rootRoute
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewImport
      parentRoute: typeof rootRoute
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/plans/new': typeof PlansNewRoute
  '/plans': typeof PlansIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/plans/new': typeof PlansNewRoute
  '/plans': typeof PlansIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/plans/new': typeof PlansNewRoute
  '/plans/': typeof PlansIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plans/$planId' | '/plans/new' | '/plans'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plans/$planId' | '/plans/new' | '/plans'
  id: '__root__' | '/' | '/plans/$planId' | '/plans/new' | '/plans/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  PlansNewRoute: typeof PlansNewRoute
  PlansIndexRoute: typeof PlansIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  PlansNewRoute: PlansNewRoute,
  PlansIndexRoute: PlansIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/plans/$planId",
        "/plans/new",
        "/plans/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/plans/$planId": {
      "filePath": "plans/$planId.tsx"
    },
    "/plans/new": {
      "filePath": "plans/new.tsx"
    },
    "/plans/": {
      "filePath": "plans/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
