/**
 * AI Weekly Summary Component
 *
 * Displays AI-generated narrative summary for a student's week.
 */

import { useState, useEffect } from "react";
import { Button } from "@/components/ui";
import { useAIInsightsStore } from "./aiInsightsStore";

interface AIWeeklySummaryProps {
  studentId: string;
  studentName: string;
  gradeLevel: string;
  weekStart: string;
  weekData: {
    totalActivities: number;
    totalMinutes: number;
    activeDays: number;
    subjectBreakdown: Array<{
      name: string;
      activities: number;
      minutes: number;
    }>;
    previousWeekActivities: number;
    previousWeekMinutes: number;
  };
}

export function AIWeeklySummary({
  studentId,
  studentName,
  gradeLevel,
  weekStart,
  weekData,
}: AIWeeklySummaryProps): JSX.Element | null {
  const {
    isInitialized,
    isAvailable,
    isGenerating,
    error,
    initialize,
    generateWeeklySummary,
    getCachedSummary,
  } = useAIInsightsStore();

  const [summary, setSummary] = useState<string | null>(null);
  const [localError, setLocalError] = useState<string | null>(null);
  const [isExpanded, setIsExpanded] = useState(false);

  // Initialize AI on mount
  useEffect(() => {
    if (!isInitialized) {
      initialize();
    }
  }, [isInitialized, initialize]);

  // Check for cached summary
  useEffect(() => {
    const cached = getCachedSummary(studentId, weekStart);
    if (cached) {
      setSummary(cached);
      setIsExpanded(true);
    }
  }, [studentId, weekStart, getCachedSummary]);

  const handleGenerateSummary = async () => {
    setLocalError(null);
    try {
      const result = await generateWeeklySummary(
        studentId,
        studentName,
        gradeLevel,
        weekStart,
        weekData,
      );
      setSummary(result);
      setIsExpanded(true);
    } catch (err) {
      setLocalError(
        err instanceof Error ? err.message : "Failed to generate summary",
      );
    }
  };

  // Don't show anything if AI is not available
  if (isInitialized && !isAvailable) {
    return (
      <div className="mt-4 p-3 bg-gray-50 rounded-lg border border-gray-200">
        <div className="flex items-center gap-2 text-sm text-gray-500">
          <svg
            className="w-4 h-4"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
            />
          </svg>
          <span>
            AI insights available with API key. Configure in Settings.
          </span>
        </div>
      </div>
    );
  }

  if (!isInitialized) {
    return null;
  }

  return (
    <div className="mt-4">
      {summary ? (
        <div
          className={`bg-gradient-to-r from-student-purple-50 to-brand-primaryLight rounded-lg border border-student-purple-100 overflow-hidden`}
        >
          <Button
            variant="ghost"
            onClick={() => setIsExpanded(!isExpanded)}
            className="w-full px-4 py-3 flex items-center justify-between hover:bg-student-purple-100/50 transition-colors rounded-none h-auto"
          >
            <div className="flex items-center gap-2">
              <span className="text-lg">✨</span>
              <span className="font-medium text-student-purple-900">
                AI Weekly Summary
              </span>
            </div>
            <svg
              className={`w-5 h-5 text-student-purple-600 transition-transform ${isExpanded ? "rotate-180" : ""}`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 9l-7 7-7-7"
              />
            </svg>
          </Button>

          {isExpanded && (
            <div className="px-4 pb-4">
              <div className="prose prose-sm prose-purple max-w-none">
                {summary.split("\n\n").map((paragraph, index) => (
                  <p key={index} className="text-gray-700 leading-relaxed">
                    {paragraph}
                  </p>
                ))}
              </div>
              <div className="mt-3 flex items-center justify-between text-xs text-student-purple-600">
                <span>Generated by AI • May contain inaccuracies</span>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleGenerateSummary}
                  disabled={isGenerating}
                  className="hover:text-student-purple-800 underline text-xs p-0 h-auto"
                >
                  Regenerate
                </Button>
              </div>
            </div>
          )}
        </div>
      ) : (
        <Button
          variant="ghost"
          onClick={handleGenerateSummary}
          disabled={isGenerating || weekData.totalActivities === 0}
          className={`w-full p-3 bg-gradient-to-r from-student-purple-50 to-brand-primaryLight rounded-lg border border-student-purple-100 hover:from-student-purple-100 hover:to-brand-primaryLight transition-colors h-auto`}
        >
          <div className="flex items-center justify-center gap-2">
            {isGenerating ? (
              <>
                <svg
                  className="animate-spin h-4 w-4 text-student-purple-600"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                <span className="text-student-purple-700">
                  Generating AI summary...
                </span>
              </>
            ) : weekData.totalActivities === 0 ? (
              <>
                <span className="text-gray-400">✨</span>
                <span className="text-gray-500">
                  No activities to summarize
                </span>
              </>
            ) : (
              <>
                <span className="text-lg">✨</span>
                <span className="text-student-purple-700 font-medium">
                  Generate AI Summary
                </span>
              </>
            )}
          </div>
        </Button>
      )}

      {(error || localError) && (
        <div className="mt-2 p-2 bg-status-errorLight border border-status-errorLight rounded text-sm text-status-error">
          {localError || error}
        </div>
      )}
    </div>
  );
}
