/**
 * Email Summary Generator
 *
 * Generates HTML and plain text email summaries for weekly digests.
 */

import { format, startOfWeek, endOfWeek } from 'date-fns'

interface StudentSummary {
  name: string
  gradeLevel: string
  totalActivities: number
  totalMinutes: number
  activeDays: number
  subjects: Array<{
    name: string
    activities: number
    minutes: number
  }>
}

interface WeeklySummaryData {
  weekStart: Date
  weekEnd: Date
  students: StudentSummary[]
  familyTotalActivities: number
  familyTotalMinutes: number
}

export function generateWeeklyEmailHTML(data: WeeklySummaryData): string {
  const weekRange = `${format(data.weekStart, 'MMMM d')} - ${format(data.weekEnd, 'MMMM d, yyyy')}`

  const studentSections = data.students
    .map(
      (student) => `
    <div style="margin-bottom: 24px; padding: 16px; background-color: #f9fafb; border-radius: 8px;">
      <h3 style="margin: 0 0 12px 0; color: #374151; font-size: 18px;">${student.name} (${student.gradeLevel})</h3>
      <div style="display: flex; gap: 16px; margin-bottom: 12px;">
        <div style="text-align: center; padding: 8px 16px; background: white; border-radius: 6px;">
          <div style="font-size: 24px; font-weight: bold; color: #4f46e5;">${student.totalActivities}</div>
          <div style="font-size: 12px; color: #6b7280;">Activities</div>
        </div>
        <div style="text-align: center; padding: 8px 16px; background: white; border-radius: 6px;">
          <div style="font-size: 24px; font-weight: bold; color: #4f46e5;">${Math.round(student.totalMinutes / 60 * 10) / 10}</div>
          <div style="font-size: 12px; color: #6b7280;">Hours</div>
        </div>
        <div style="text-align: center; padding: 8px 16px; background: white; border-radius: 6px;">
          <div style="font-size: 24px; font-weight: bold; color: #4f46e5;">${student.activeDays}</div>
          <div style="font-size: 12px; color: #6b7280;">Days Active</div>
        </div>
      </div>
      ${
        student.subjects.length > 0
          ? `
        <div style="margin-top: 12px;">
          <div style="font-size: 14px; font-weight: 500; color: #6b7280; margin-bottom: 8px;">By Subject:</div>
          ${student.subjects
            .map(
              (subject) => `
            <div style="display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px solid #e5e7eb;">
              <span style="color: #374151;">${subject.name}</span>
              <span style="color: #6b7280;">${subject.activities} activities, ${Math.round(subject.minutes)} min</span>
            </div>
          `
            )
            .join('')}
        </div>
      `
          : '<p style="color: #9ca3af; font-style: italic;">No activities this week</p>'
      }
    </div>
  `
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Homeschool Summary</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 0; background-color: #f3f4f6;">
  <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); color: white; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
      <h1 style="margin: 0; font-size: 24px;">Weekly Homeschool Summary</h1>
      <p style="margin: 8px 0 0 0; opacity: 0.9;">${weekRange}</p>
    </div>

    <!-- Main Content -->
    <div style="background: white; padding: 24px; border-radius: 0 0 12px 12px;">
      <!-- Family Overview -->
      <div style="text-align: center; margin-bottom: 24px; padding-bottom: 24px; border-bottom: 2px solid #e5e7eb;">
        <h2 style="margin: 0 0 16px 0; color: #1f2937; font-size: 20px;">Family Overview</h2>
        <div style="display: inline-flex; gap: 32px;">
          <div>
            <div style="font-size: 36px; font-weight: bold; color: #4f46e5;">${data.familyTotalActivities}</div>
            <div style="font-size: 14px; color: #6b7280;">Total Activities</div>
          </div>
          <div>
            <div style="font-size: 36px; font-weight: bold; color: #4f46e5;">${Math.round(data.familyTotalMinutes / 60 * 10) / 10}</div>
            <div style="font-size: 14px; color: #6b7280;">Total Hours</div>
          </div>
        </div>
      </div>

      <!-- Student Sections -->
      ${studentSections}

      <!-- Footer -->
      <div style="margin-top: 24px; padding-top: 24px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px;">
        <p>Generated by Homeschool App</p>
        <p style="margin-top: 4px;">Keep up the great work!</p>
      </div>
    </div>
  </div>
</body>
</html>
  `.trim()
}

export function generateWeeklyEmailPlainText(data: WeeklySummaryData): string {
  const weekRange = `${format(data.weekStart, 'MMMM d')} - ${format(data.weekEnd, 'MMMM d, yyyy')}`

  const studentSections = data.students
    .map((student) => {
      const subjectLines =
        student.subjects.length > 0
          ? student.subjects.map((s) => `  - ${s.name}: ${s.activities} activities, ${Math.round(s.minutes)} min`).join('\n')
          : '  No activities this week'

      return `
${student.name} (${student.gradeLevel})
${'='.repeat(student.name.length + student.gradeLevel.length + 3)}
Activities: ${student.totalActivities}
Hours: ${Math.round(student.totalMinutes / 60 * 10) / 10}
Days Active: ${student.activeDays}

By Subject:
${subjectLines}
`
    })
    .join('\n')

  return `
WEEKLY HOMESCHOOL SUMMARY
${weekRange}
${'='.repeat(50)}

FAMILY OVERVIEW
---------------
Total Activities: ${data.familyTotalActivities}
Total Hours: ${Math.round(data.familyTotalMinutes / 60 * 10) / 10}

STUDENT DETAILS
---------------
${studentSections}

---
Generated by Homeschool App
Keep up the great work!
  `.trim()
}

export function generateEmailSubject(weekStart: Date): string {
  return `Weekly Homeschool Summary - Week of ${format(weekStart, 'MMMM d, yyyy')}`
}
