exports.config = {
  runner: 'local',
  port: 4723,
  specs: [
    './specs/smoke.spec.js',
    './specs/today.spec.js',
    './specs/log.spec.js',
    './specs/progress.spec.js',
    './specs/calendar.spec.js',
    './specs/field-trips.spec.js',
    './specs/activities.spec.js',
    './specs/library.spec.js',
    './specs/milestones.spec.js',
    './specs/planner.spec.js',
    './specs/reports.spec.js',
    './specs/settings.spec.js',
  ],
  exclude: ['./specs/debug-*.spec.js'],
  maxInstances: 1,
  capabilities: [
    {
      platformName: 'iOS',
      'appium:automationName': 'XCUITest',
      'appium:deviceName': 'iPhone 17 Pro',
      'appium:udid': '61185A47-BE90-4A2B-A9D5-C9374866B6A9',
      'appium:bundleId': 'com.scoblelife.homeschool',
      'appium:noReset': true,
      'appium:usePreinstalledApp': true,
    },
  ],
  logLevel: 'warn',
  waitforTimeout: 10000,
  connectionRetryTimeout: 60000,
  connectionRetryCount: 3,
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 180000,
  },
}
